# Generated by Django 4.2 on 2023-09-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0002_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ouruser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
