# Generated by Django 4.2.4 on 2023-09-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catagory",
            old_name="slug",
            new_name="cat_slug",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="slug",
            new_name="pro_slug",
        ),
    ]
