# Generated by Django 4.2.4 on 2023-09-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_catagory_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catagory",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",)},
        ),
    ]
