# Generated by Django 4.2.4 on 2023-09-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_catagory_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forcart",
            options={"ordering": ("name",)},
        ),
    ]
