# Generated by Django 4.2.4 on 2023-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_forcart_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forcart",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
