# Generated by Django 4.2 on 2023-06-10 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("CR", "Curd"),
                    ("ML", "Milk"),
                    ("LS", "Lassi"),
                    ("MS", "Milikshake"),
                    ("PN", "Paneer"),
                    ("CZ", "Cheese"),
                    ("IC", "Ice-Cream"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("mobile", models.IntegerField()),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("P", "punjab"),
                            ("S", "sindh"),
                            ("K", "KPK"),
                            ("B", "balochistan"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
