# Generated by Django 4.2 on 2023-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0002_alter_product_category_alter_product_discount_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.FloatField(max_length=200),
        ),
    ]
