# Generated by Django 5.0.1 on 2024-02-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_alter_quiz_options_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
