# Generated by Django 5.0.1 on 2024-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='vedio_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'Article'), ('quiz', 'Quiz'), ('vedio', 'Vedio')], default='article', max_length=20),
        ),
    ]
