# Generated by Django 5.0.1 on 2024-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_alter_lesson_long_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='vedio_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
